# 是否啟用此插件
ban-enable: true

# 你的伺服器代號（例如 catbud.net）
server-id: example.com

# 當玩家被踢出時顯示的訊息
#   使用 https://docs.advntr.dev/minimessage/format.html
kick-message: <lang:multiplayer.disconnect.banned>

# API 調用網址
#   %server% 將會替換成你的 server 配置。
#   %player% 則是在登入時檢查玩家是否被你選擇加入封鎖。
api-url: https://mcban.tw/api/query?server=%server%&player=%player%

# 如果 API 訪問出現錯誤
#   true = 拒絕所有登入，直到 API 恢復為止。
#   false = 忽略檢查。
exception-denied: true